-- Migration: adds the HANDBOOKSECTION table for the handbook-grounded
-- chatbot feature. Run this once against your existing Oracle schema
-- (hibernate.ddl-auto is set to "validate", so it will NOT be created
-- automatically -- you must run this yourself before starting the backend).
--
-- Usage (SQL*Plus / SQL Developer, connected as the rcosd schema user):
--   @scripts/add_handbooksection_table.sql

CREATE TABLE HANDBOOKSECTION (
    HANDBOOKSECTIONID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DEPARTMENT VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(500),
    BODY CLOB,
    ORDERINDEX NUMBER
);
