DEFINE v_record_id = 22;

DELETE FROM APPEAL WHERE RECORDID = &v_record_id;

UPDATE RECORD
SET STATUS = 'PENDING'
WHERE RECORDID = &v_record_id;

COMMIT;


DEFINE v_student_id = 'CT23-0006';

INSERT INTO RECORD (
    ENROLLMENTID,
    EMPLOYEEID,
    OFFENSEID,
    DATEOFVIOLATION,
    ACTIONID,
    REMARKS,
    STATUS
)
SELECT
    (SELECT ENROLLMENTID FROM ENROLLMENT
       WHERE STUDENTID = '&v_student_id'
       ORDER BY ENROLLMENTID DESC FETCH FIRST 1 ROWS ONLY),
    (SELECT EMPLOYEEID FROM EMPLOYEE FETCH FIRST 1 ROWS ONLY),
    (SELECT OFFENSEID FROM OFFENSE FETCH FIRST 1 ROWS ONLY),
    TRUNC(SYSDATE),
    (SELECT ACTIONID FROM DISCIPLINARYACTION FETCH FIRST 1 ROWS ONLY),
    'QA test record for appeal flow',
    'PENDING'
FROM DUAL;

COMMIT;

SELECT r.RECORDID, r.STATUS, o.OFFENSE AS OFFENSE_NAME, e.STUDENTID
FROM RECORD r
JOIN ENROLLMENT e ON e.ENROLLMENTID = r.ENROLLMENTID
JOIN OFFENSE o ON o.OFFENSEID = r.OFFENSEID
WHERE e.STUDENTID = '&v_student_id'
ORDER BY r.RECORDID DESC
FETCH FIRST 1 ROWS ONLY;


DEFINE v_student_id_check = 'CT23-0006';

SELECT
    r.RECORDID,
    r.STATUS       AS RECORD_STATUS,
    o.OFFENSE      AS OFFENSE_NAME,
    a.APPEALID,
    a.STATUS       AS APPEAL_STATUS,
    a.DATEFILED
FROM RECORD r
JOIN ENROLLMENT e ON e.ENROLLMENTID = r.ENROLLMENTID
JOIN OFFENSE o ON o.OFFENSEID = r.OFFENSEID
LEFT JOIN APPEAL a ON a.RECORDID = r.RECORDID
WHERE e.STUDENTID = '&v_student_id_check'
ORDER BY r.RECORDID DESC;
